#Conexión a BBDD
url=jdbc:mysql://localhost:3306/cronometro_db?useSSL=false
username=root
password=root

#Correo
email-user=rubiktimer@outlook.com
email-password=jaximus1@

#url=jdbc:mysql://localhost/dertimer_cronometro_db?useSSL=false
#username=dertimer_admin
#password=ThornyTrowelMaidenTroika67

#email-user=support@der-timer.com
#email-password=Jaximus1@