#Conexión a BBDD
url=jdbc:mysql://localhost/dertimer_cronometro_db?useSSL=false
username=dertimer_admin
password=ThornyTrowelMaidenTroika67

#Correo
email-user=support@der-timer.com
email-password=Jaximus1@