#Conexión a BBDD
url=jdbc:mysql://bd:3306/cronometro_db?useSSL=false&allowPublicKeyRetrieval=true
username=root
password=Vr6p@gXso609CB*dBNn5

#Correo
email-user=rubiktimer@outlook.com
email-password=jaximus1@

#url=jdbc:mysql://localhost/dertimer_cronometro_db?useSSL=false
#username=dertimer_admin
#password=ThornyTrowelMaidenTroika67

#email-user=support@der-timer.com
#email-password=Jaximus1@